# Generated by Django 2.2.2 on 2019-07-16 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Register',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(help_text='Enter the User Name', max_length=255)),
                ('password', models.CharField(help_text='Enter Password', max_length=255)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female')], default='male', help_text='Enter Gender', max_length=255)),
                ('email', models.EmailField(help_text='Enter Email', max_length=255)),
                ('idproof', models.CharField(choices=[('aadhar card', 'Aadhar Card'), ('pan card', 'PAN Card'), ('voter id card', 'Voter ID Card')], default='aadhar card', help_text='Enter ID Number', max_length=12)),
                ('idnum', models.CharField(help_text='Enter the Aadhar Card No./PAN Card No./Voter ID No.', max_length=12)),
                ('mobile', models.IntegerField()),
                ('city', models.CharField(help_text='Enter City', max_length=255)),
                ('address', models.TextField(help_text='Enter Address', max_length=255)),
                ('state', models.CharField(help_text='Enter State', max_length=255)),
                ('pincode', models.IntegerField()),
                ('country', models.CharField(help_text='Enter Country', max_length=255)),
            ],
            options={
                'verbose_name': 'Register',
                'verbose_name_plural': 'Registers',
                'db_table': 'Registration',
                'ordering': ('username',),
            },
        ),
    ]
