# Generated by Django 2.2.2 on 2019-07-18 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Query',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(help_text='Enter the User Name', max_length=255)),
                ('email', models.EmailField(help_text='Enter Email', max_length=255)),
                ('mobile', models.IntegerField()),
                ('query', models.TextField(help_text='Enter Address', max_length=255)),
            ],
            options={
                'verbose_name': 'Contact',
                'verbose_name_plural': 'Contacts',
                'db_table': 'Contactus',
                'ordering': ('username',),
            },
        ),
    ]
