# Generated by Django 2.2.2 on 2019-07-29 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_remove_register_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='register',
            name='password',
            field=models.CharField(default=1, help_text='Enter Password', max_length=255),
            preserve_default=False,
        ),
    ]
