# Generated by Django 2.2.2 on 2019-07-31 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0016_auto_20190730_1600'),
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='card')),
                ('description', models.TextField()),
                ('title', models.TextField()),
            ],
        ),
    ]
