# Generated by Django 2.2.2 on 2019-07-31 11:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0017_card'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booked',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person', models.TextField()),
                ('current', models.DateField()),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='myapp.Packages')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='myapp.Register')),
            ],
        ),
        migrations.DeleteModel(
            name='Booking',
        ),
    ]
